# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r_packages:
  - knitr
  - rmarkdown
  - devtools
  - roxygen2

r:
  - release

before_install:
  - git clone http://microb98.med.upenn.edu/bitbucket/scm/sarc/data_files.git ~/data_files

script:
  - Rscript -e 'devtools::check()'
#  - Rscript -e 'rmarkdown::render(system.file("generate_figures.Rmd", package="SarcoidMicrobiome"), params=list(data_fp="/home/travis/data_files"))'
  - Rscript -e 'rmarkdown::render(system.file("generate_figures.Rmd", package="SarcoidMicrobiome"))'
