# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r_packages:
 - knitr

r:
 - release

script:
  - git clone http://microb98.med.upenn.edu/bitbucket/scm/sarc/data_files.git ~/data_files
  - Rscript -e 'knitr::knit(system.file("generate_figures.Rmd", package="SarcoidMicrobiome"))'
